// @ts-nocheck
import { useState } from "react"
import { IndexTable, Card, Text, Badge, Box, InlineStack, Avatar, Button, Pagination } from "@/components/ui/admin-primitives"
import { calculateTotal, formatDate } from "../orders.utils"
import { Order } from "../types/orders.types"
import PrepareOrderModal from "./prepare-order-modal"

interface PaginationInfo { total: number; page: number; limit: number; totalPages: number }
type OrdersTableProps = { orders: Order[]; onSelectOrder: (order: Order) => void; pagination: PaginationInfo; onPageChange: (page: number) => void }
const getInitials = (name?: string) => { if (!name) return "?"; const parts = name.trim().split(/\s+/); return (parts[0]?.[0] ?? "").concat(parts[1]?.[0] ?? "").toUpperCase() }
const OrdersTable = ({ orders, onSelectOrder, pagination, onPageChange }: OrdersTableProps) => {
  const [show, setShow] = useState(false); const [selectedOrder, setSelectedOrder] = useState<Order | null>(null)
  const getFulfillmentTone = (status?: string | null) => status?.toLowerCase() === "fulfilled" ? "success" : status?.toLowerCase() === "partially_fulfilled" ? "warning" : "attention"
  const getShippingTone = (status?: string) => status?.toLowerCase() === "delivered" ? "success" : status?.toLowerCase() === "in_transit" ? "progress" : status?.toLowerCase() === "label_purchased" ? "info" : "subdued"
  return <div dir="ltr" className="w-full">{show && selectedOrder && <PrepareOrderModal order={selectedOrder} onClose={() => { setShow(false); setSelectedOrder(null) }} />}
    <Box paddingBlockEnd="400"><InlineStack align="space-between" blockAlign="center"><div><Text variant="headingMd" as="h2">Recent orders</Text><Text tone="subdued" className="mt-1 block text-sm">Your latest storefront activity</Text></div><Badge tone="info">{pagination.total} total</Badge></InlineStack></Box>
    <div className="w-full overflow-x-auto"><Card padding="0"><IndexTable headings={[{ title: "Order" }, { title: "Customer" }, { title: "Store" }, { title: "Items" }, { title: "Total" }, { title: "Fulfillment" }, { title: "Shipping" }, { title: "Action" }]}>{orders.map((order, index) => { const orderId = order._id?.$oid || order.shopifyOrderId; const totalAmount = calculateTotal(order.orderItems); const currency = order.orderItems?.[0]?.price_set?.shop_money?.currency_code || "USD"; return <IndexTable.Row id={String(orderId)} key={String(orderId)} position={index} onClick={() => onSelectOrder(order)}><IndexTable.Cell><Text fontWeight="bold" as="span" className="text-primary">#{order.shopifyOrderId}</Text></IndexTable.Cell><IndexTable.Cell><InlineStack gap="300" blockAlign="center"><Avatar name={order.customerName || "Customer"} initials={getInitials(order.customerName)} /><Box><Text fontWeight="semibold" as="span">{order.customerName || "No Name"}</Text><Box><Text tone="subdued" as="span" className="text-xs">{formatDate(order.createdAt)}</Text></Box></Box></InlineStack></IndexTable.Cell><IndexTable.Cell><Text tone="subdued" as="span" className="max-w-40 truncate">{order.storeUrl}</Text></IndexTable.Cell><IndexTable.Cell><Text className="font-medium">{order.orderItems?.length || 0}</Text></IndexTable.Cell><IndexTable.Cell><Text fontWeight="semibold" as="span">{totalAmount.toLocaleString()} {currency}</Text></IndexTable.Cell><IndexTable.Cell><Badge tone={getFulfillmentTone(order.fulfillmentStatus)}>{order.fulfillmentStatus === "partially_fulfilled" ? "Partial" : order.fulfillmentStatus || "Unfulfilled"}</Badge></IndexTable.Cell><IndexTable.Cell><Badge tone={getShippingTone(order.shippingStatus)}>{order.shippingStatus === "label_purchased" ? "Label Ready" : order.shippingStatus || "Pending"}</Badge></IndexTable.Cell><IndexTable.Cell><div onClick={(e) => e.stopPropagation()}><Button size="slim" variant="primary" onClick={() => { setSelectedOrder(order); setShow(true) }}>Prepare order</Button></div></IndexTable.Cell></IndexTable.Row> })}</IndexTable></Card></div>
    {pagination.totalPages > 1 && <Box paddingBlockStart="400"><InlineStack align="center"><Pagination hasPrevious={pagination.page > 1} onPrevious={() => onPageChange(pagination.page - 1)} hasNext={pagination.page < pagination.totalPages} onNext={() => onPageChange(pagination.page + 1)} label={`Page ${pagination.page} of ${pagination.totalPages}`} /></InlineStack></Box>}
  </div>
}
export default OrdersTable
